name: blueprint_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  #
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  #
  easy_localization: ^3.0.7
  #
  get_it: ^7.7.0
  go_router: ^14.1.1
  flutter_hooks: ^0.20.5
  json_annotation: ^4.9.0
  spider: ^4.2.2
  google_fonts: ^6.2.1
  cupertino_back_gesture: ^0.1.0
  cupertino_icons: ^1.0.8
  hive_generator: ^2.0.1

dev_dependencies:
  build_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/translations/
    - assets/fonts/

  fonts:
    - family: ThisAppIcons
      fonts:
        - asset: assets/fonts/ThisAppIcons.ttf
