name: blueprint_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_back_gesture: ^0.1.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  get_it: ^7.7.0
  go_router: ^14.1.1
  google_fonts: ^6.2.1
  isar: ^3.1.0+1
  json_annotation: ^4.9.0

  provider: ^6.1.2
  shared_preferences: ^2.2.3
  spider: ^4.2.2

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner:
  #  ^2.4.10
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/translations/
    - assets/fonts/

  fonts:
    - family: ThisAppIcons
      fonts:
        - asset: assets/fonts/ThisAppIcons.ttf
