import 'package:flutter/material.dart';

import 'custom_icons_source.dart';

class ThisAppCustomIcons {
  static const List<IconData> _myCustomIconList = [
    ThisAppCustomIconsSource.alert,
    ThisAppCustomIconsSource.anchor,
    ThisAppCustomIconsSource.archive,
    ThisAppCustomIconsSource.arrowBoth,
    ThisAppCustomIconsSource.arrowDown,
    ThisAppCustomIconsSource.arrowLeft,
    ThisAppCustomIconsSource.arrowRight,
    ThisAppCustomIconsSource.arrowSmallDown,
    ThisAppCustomIconsSource.arrowSmallLeft,
    ThisAppCustomIconsSource.arrowSmallRight,
    ThisAppCustomIconsSource.arrowSmallUp,
    ThisAppCustomIconsSource.arrowUp,
    ThisAppCustomIconsSource.at,
    ThisAppCustomIconsSource.attach,
    ThisAppCustomIconsSource.attention,
    ThisAppCustomIconsSource.attentionAlt,
    ThisAppCustomIconsSource.beaker,
    ThisAppCustomIconsSource.bell,
    ThisAppCustomIconsSource.bellAlt,
    ThisAppCustomIconsSource.book,
    ThisAppCustomIconsSource.bookmark,
    ThisAppCustomIconsSource.briefcase,
    ThisAppCustomIconsSource.browser,
    ThisAppCustomIconsSource.bug,
    ThisAppCustomIconsSource.cancel,
    ThisAppCustomIconsSource.cancelCircled,
    ThisAppCustomIconsSource.calendar,
    ThisAppCustomIconsSource.calendarAlt,
    ThisAppCustomIconsSource.camera,
    ThisAppCustomIconsSource.chartBar,
    ThisAppCustomIconsSource.check,
    ThisAppCustomIconsSource.checklist,
    ThisAppCustomIconsSource.chevronDown,
    ThisAppCustomIconsSource.chevronLeft,
    ThisAppCustomIconsSource.chevronRight,
    ThisAppCustomIconsSource.chevronUp,
    ThisAppCustomIconsSource.chrome,
    ThisAppCustomIconsSource.circleSlash,
    ThisAppCustomIconsSource.clippy,
    ThisAppCustomIconsSource.clock,
    ThisAppCustomIconsSource.clockAlt,
    ThisAppCustomIconsSource.cloud,
    ThisAppCustomIconsSource.cloudDownload,
    ThisAppCustomIconsSource.cloudUpload,
    ThisAppCustomIconsSource.cog,
    ThisAppCustomIconsSource.colorAdjust,
    ThisAppCustomIconsSource.comment,
    ThisAppCustomIconsSource.commentAlt,
    ThisAppCustomIconsSource.commentDiscussion,
    ThisAppCustomIconsSource.connectedObject,
    ThisAppCustomIconsSource.console,
    ThisAppCustomIconsSource.coverFlow,
    ThisAppCustomIconsSource.coverFlowEmpty,
    ThisAppCustomIconsSource.creditCard,
    ThisAppCustomIconsSource.crown,
    ThisAppCustomIconsSource.crownMinus,
    ThisAppCustomIconsSource.crownPlus,
    ThisAppCustomIconsSource.css,
    ThisAppCustomIconsSource.dashboard,
    ThisAppCustomIconsSource.dataScience,
    ThisAppCustomIconsSource.dataScienceInv,
    ThisAppCustomIconsSource.database,
    ThisAppCustomIconsSource.dependent,
    ThisAppCustomIconsSource.desktopDownload,
    ThisAppCustomIconsSource.deviceCamera,
    ThisAppCustomIconsSource.deviceCameraVideo,
    ThisAppCustomIconsSource.deviceDesktop,
    ThisAppCustomIconsSource.deviceMobile,
    ThisAppCustomIconsSource.diff,
    ThisAppCustomIconsSource.diffAdded,
    ThisAppCustomIconsSource.diffIgnored,
    ThisAppCustomIconsSource.diffModified,
    ThisAppCustomIconsSource.diffRemoved,
    ThisAppCustomIconsSource.diffRenamed,
    ThisAppCustomIconsSource.doc,
    ThisAppCustomIconsSource.download,
    ThisAppCustomIconsSource.downloadCloud,
    ThisAppCustomIconsSource.downBold,
    ThisAppCustomIconsSource.downFat,
    ThisAppCustomIconsSource.downOpen,
    ThisAppCustomIconsSource.down,
    ThisAppCustomIconsSource.ellipsis,
    ThisAppCustomIconsSource.emoAngry,
    ThisAppCustomIconsSource.emoBeer,
    ThisAppCustomIconsSource.emoCoffee,
    ThisAppCustomIconsSource.emoCry,
    ThisAppCustomIconsSource.emoDevil,
    ThisAppCustomIconsSource.emoDispleased,
    ThisAppCustomIconsSource.emoGrin,
    ThisAppCustomIconsSource.emoHappy,
    ThisAppCustomIconsSource.emoLaugh,
    ThisAppCustomIconsSource.emoSaint,
    ThisAppCustomIconsSource.emoShoot,
    ThisAppCustomIconsSource.emoSleep,
    ThisAppCustomIconsSource.emoSquint,
    ThisAppCustomIconsSource.emoSunglasses,
    ThisAppCustomIconsSource.emoSurprised,
    ThisAppCustomIconsSource.emoThumbsup,
    ThisAppCustomIconsSource.emoTongue,
    ThisAppCustomIconsSource.emoUnhappy,
    ThisAppCustomIconsSource.emoWink,
    ThisAppCustomIconsSource.emoWinkAlt,
    ThisAppCustomIconsSource.export,
    ThisAppCustomIconsSource.eye,
    ThisAppCustomIconsSource.eyeAlt,
    ThisAppCustomIconsSource.eyeClosed,
    ThisAppCustomIconsSource.fileBinary,
    ThisAppCustomIconsSource.fileCode,
    ThisAppCustomIconsSource.fileDirectory,
    ThisAppCustomIconsSource.fileMedia,
    ThisAppCustomIconsSource.filePdf,
    ThisAppCustomIconsSource.fileSubmodule,
    ThisAppCustomIconsSource.fileSymlinkDirectory,
    ThisAppCustomIconsSource.fileSymlinkFile,
    ThisAppCustomIconsSource.fileZip,
    ThisAppCustomIconsSource.fire,
    ThisAppCustomIconsSource.flash,
    ThisAppCustomIconsSource.fold,
    ThisAppCustomIconsSource.foldDown,
    ThisAppCustomIconsSource.folder,
    ThisAppCustomIconsSource.folderEmpty,
    ThisAppCustomIconsSource.folderOpen,
    ThisAppCustomIconsSource.folderOpenEmpty,
    ThisAppCustomIconsSource.foldUp,
    ThisAppCustomIconsSource.fontSize,
    // ThisAppCustomIconsSource.fuel,
    ThisAppCustomIconsSource.gift,
    ThisAppCustomIconsSource.github,
    ThisAppCustomIconsSource.githubAction,
    ThisAppCustomIconsSource.githubCircled,
    ThisAppCustomIconsSource.githubCircledAlt,
    ThisAppCustomIconsSource.githubCircledAlt2,
    ThisAppCustomIconsSource.gist,
    ThisAppCustomIconsSource.gistSecret,
    ThisAppCustomIconsSource.gitBranch,
    ThisAppCustomIconsSource.gitCommit,
    ThisAppCustomIconsSource.gitCompare,
    ThisAppCustomIconsSource.gitMerge,
    ThisAppCustomIconsSource.gitPullRequest,
    ThisAppCustomIconsSource.globe,
    ThisAppCustomIconsSource.globeAlt,
    ThisAppCustomIconsSource.globeInv,
    ThisAppCustomIconsSource.graph,
    ThisAppCustomIconsSource.hash,
    ThisAppCustomIconsSource.heart,
    ThisAppCustomIconsSource.heartAlt,
    ThisAppCustomIconsSource.heartBroken,
    ThisAppCustomIconsSource.heartOutline,
    ThisAppCustomIconsSource.helpCircled,
    // ThisAppCustomIconsSource.helpCircledAlt,
    ThisAppCustomIconsSource.history,
    ThisAppCustomIconsSource.home,
    ThisAppCustomIconsSource.homeAlt,
    ThisAppCustomIconsSource.hourglass,
    ThisAppCustomIconsSource.hubot,
    ThisAppCustomIconsSource.inbox,
    ThisAppCustomIconsSource.inboxAlt,
    ThisAppCustomIconsSource.infinity,
    ThisAppCustomIconsSource.info,
    ThisAppCustomIconsSource.infoCircled,
    ThisAppCustomIconsSource.infoCircledAlt,
    ThisAppCustomIconsSource.internalRepo,
    ThisAppCustomIconsSource.isSight,
    ThisAppCustomIconsSource.issueClosed,
    ThisAppCustomIconsSource.issueOpened,
    ThisAppCustomIconsSource.issueReOpened,
    // ThisAppCustomIconsSource.it,
    // ThisAppCustomIconsSource.itAlt,
    ThisAppCustomIconsSource.jersey,
    ThisAppCustomIconsSource.joystick,
    // ThisAppCustomIconsSource.js,
    // ThisAppCustomIconsSource.jsAlt,
    ThisAppCustomIconsSource.key,
    ThisAppCustomIconsSource.keyboard,
    ThisAppCustomIconsSource.king,
    // ThisAppCustomIconsSource.laptop,
    ThisAppCustomIconsSource.leftBold,
    ThisAppCustomIconsSource.leftFat,
    ThisAppCustomIconsSource.leftOpen,
    ThisAppCustomIconsSource.left,
    ThisAppCustomIconsSource.lineArrowDown,
    ThisAppCustomIconsSource.lineArrowLeft,
    ThisAppCustomIconsSource.lineArrowRight,
    ThisAppCustomIconsSource.lineArrowUp,
    ThisAppCustomIconsSource.link,
    ThisAppCustomIconsSource.linkAlt,
    ThisAppCustomIconsSource.linkAlt,
    ThisAppCustomIconsSource.linkExternal,
    ThisAppCustomIconsSource.listOrdered,
    ThisAppCustomIconsSource.listUnordered,
    ThisAppCustomIconsSource.location,
    ThisAppCustomIconsSource.locationAlt,
    ThisAppCustomIconsSource.lock,
    ThisAppCustomIconsSource.lockAlt,
    ThisAppCustomIconsSource.lockAlt2,
    ThisAppCustomIconsSource.lockOpen,
    ThisAppCustomIconsSource.lockOpenAlt,
    ThisAppCustomIconsSource.logIn,
    ThisAppCustomIconsSource.logOut,
    ThisAppCustomIconsSource.mail,
    ThisAppCustomIconsSource.mailAlt,
    ThisAppCustomIconsSource.mailRead,
    ThisAppCustomIconsSource.male,
    ThisAppCustomIconsSource.map,
    ThisAppCustomIconsSource.markdown,
    ThisAppCustomIconsSource.markGithub,
    ThisAppCustomIconsSource.marquee,
    ThisAppCustomIconsSource.math,
    ThisAppCustomIconsSource.mathCircled,
    ThisAppCustomIconsSource.mathCircledEmpty,
    ThisAppCustomIconsSource.megaphone,
    ThisAppCustomIconsSource.menu,
    ThisAppCustomIconsSource.mfgLogo,
    ThisAppCustomIconsSource.mfgLogoCircled,
    ThisAppCustomIconsSource.microchip,
    ThisAppCustomIconsSource.microphone,
    // ThisAppCustomIconsSource.microphoneAlt,
    // ThisAppCustomIconsSource.microphoneAlt2,
    ThisAppCustomIconsSource.microphoneAlt3,
    ThisAppCustomIconsSource.microphoneAlt4,
    // ThisAppCustomIconsSource.microphoneAlt5,
    ThisAppCustomIconsSource.microphoneAlt7,
    ThisAppCustomIconsSource.microphoneAlt8,
    ThisAppCustomIconsSource.microphoneAlt9,
    ThisAppCustomIconsSource.microphoneOff,
    ThisAppCustomIconsSource.microphoneSlash,
    ThisAppCustomIconsSource.microphoneSlash2,
    ThisAppCustomIconsSource.microphoneSlash3,
    ThisAppCustomIconsSource.microphoneSlash4,
    ThisAppCustomIconsSource.microphoneSlash5,
    ThisAppCustomIconsSource.mirror,
    ThisAppCustomIconsSource.minus,
    ThisAppCustomIconsSource.minusAlt,
    ThisAppCustomIconsSource.minusAlt2,
    ThisAppCustomIconsSource.minusAlt3,
    ThisAppCustomIconsSource.minusAlt4,
    ThisAppCustomIconsSource.minusCircled,
    ThisAppCustomIconsSource.minusCircledAlt,
    ThisAppCustomIconsSource.minusCircledAlt2,
    ThisAppCustomIconsSource.minusCircledAlt3,
    ThisAppCustomIconsSource.minusCircledAlt4,
    ThisAppCustomIconsSource.minusSmall,
    ThisAppCustomIconsSource.minusSmallAlt,
    ThisAppCustomIconsSource.minusSmallAlt2,
    ThisAppCustomIconsSource.minusSmallAlt3,
    ThisAppCustomIconsSource.minusSmallAlt,
    ThisAppCustomIconsSource.monitor,
    ThisAppCustomIconsSource.mortarBoard,
    // ThisAppCustomIconsSource.mousePointer,
    ThisAppCustomIconsSource.movie,
    // ThisAppCustomIconsSource.musicNote,
    // ThisAppCustomIconsSource.musicNoteAlt,
    // ThisAppCustomIconsSource.musicNoteAlt2,
    // ThisAppCustomIconsSource.musicNoteAlt3,
    // ThisAppCustomIconsSource.musicNoteAlt4,
    // ThisAppCustomIconsSource.musicNoteAlt5,
    // ThisAppCustomIconsSource.musicNoteAlt6,
    // ThisAppCustomIconsSource.musicNoteAlt7,
    // ThisAppCustomIconsSource.musicNoteAlt8,
    // ThisAppCustomIconsSource.musicNoteAlt9,
    // ThisAppCustomIconsSource.musicNoteAltSlash,
    // ThisAppCustomIconsSource.musicNoteAltSlash2,
    // ThisAppCustomIconsSource.musicNoteAltSlash3,
    // ThisAppCustomIconsSource.musicNoteAltSlash4,
    // ThisAppCustomIconsSource.musicNoteAltSlash5,
    // ThisAppCustomIconsSource.musicNoteSlash,
    // ThisAppCustomIconsSource.musicNoteSlash2,
    // ThisAppCustomIconsSource.musicNoteSlash3,
    // ThisAppCustomIconsSource.musicNoteSlash4,
    // ThisAppCustomIconsSource.musicNoteSlash5,
    // ThisAppCustomIconsSource.myCustomIconList,
    // ThisAppCustomIconsSource.navbar,
    // ThisAppCustomIconsSource.navbarAlt,
    // ThisAppCustomIconsSource.navbarAlt2,
    // ThisAppCustomIconsSource.navbarAlt3,
    // ThisAppCustomIconsSource.navbarAlt4,
    // ThisAppCustomIconsSource.navbarAlt5,
    // ThisAppCustomIconsSource.navbarAlt6,
    // ThisAppCustomIconsSource.navbarAlt7,
    // ThisAppCustomIconsSource.navbarAlt8,
    // ThisAppCustomIconsSource.navbarAlt9,
    ThisAppCustomIconsSource.note,
    // ThisAppCustomIconsSource.notebook,
    // ThisAppCustomIconsSource.notebookAlt,
    // ThisAppCustomIconsSource.notebookAlt2,
    // ThisAppCustomIconsSource.notebookAlt3,
    // ThisAppCustomIconsSource.notebookAlt4,
    // ThisAppCustomIconsSource.notebookAlt5,
    // ThisAppCustomIconsSource.notebookSlash,
    // ThisAppCustomIconsSource.notebookSlash2,
    // ThisAppCustomIconsSource.notebookSlash3,
    // ThisAppCustomIconsSource.notebookSlash4,
    // ThisAppCustomIconsSource.notebookSlash5,
    // ThisAppCustomIconsSource.notebookAlt6,
    // ThisAppCustomIconsSource.notebookAlt7,
    // ThisAppCustomIconsSource.notebookAlt8,
    // ThisAppCustomIconsSource.notebookAlt9,
    // ThisAppCustomIconsSource.notebookAlt10,
    // ThisAppCustomIconsSource.noteSlash,
    // ThisAppCustomIconsSource.noteSlash2,
    // ThisAppCustomIconsSource.noteSlash3,
    // ThisAppCustomIconsSource.noteSlash4,
    // ThisAppCustomIconsSource.noteSlash5,
    ThisAppCustomIconsSource.paintCan,
    // ThisAppCustomIconsSource.paperClip,
    // ThisAppCustomIconsSource.paperClipAlt,
    // ThisAppCustomIconsSource.paperClipAlt2,
    // ThisAppCustomIconsSource.paperClipAlt3,
    // ThisAppCustomIconsSource.paperClipAlt4,
    // ThisAppCustomIconsSource.paperClipAlt5,
    // ThisAppCustomIconsSource.paperClipAlt6,
    // ThisAppCustomIconsSource.paperClipAlt7,
    // ThisAppCustomIconsSource.paperClipAlt8,
    // ThisAppCustomIconsSource.paperClipAlt9,
    // ThisAppCustomIconsSource.paperClipAlt10,
    // ThisAppCustomIconsSource.paperClipSlash,
    // ThisAppCustomIconsSource.paperClipSlash2,
    // ThisAppCustomIconsSource.paperClipSlash3,
    // ThisAppCustomIconsSource.paperClipSlash4,
    // ThisAppCustomIconsSource.paperClipSlash5,
    ThisAppCustomIconsSource.paperPlane,
    ThisAppCustomIconsSource.paperPlaneAlt,
    ThisAppCustomIconsSource.paperPlaneAlt2,
    ThisAppCustomIconsSource.pause,
    ThisAppCustomIconsSource.pencil,
    ThisAppCustomIconsSource.pencilAlt,
    ThisAppCustomIconsSource.person,
    ThisAppCustomIconsSource.pin,
    // ThisAppCustomIconsSource.pinboard,
    // ThisAppCustomIconsSource.pinboardAlt1,
    // ThisAppCustomIconsSource.pinboardAlt2,
    // ThisAppCustomIconsSource.pinboardAlt3,
    // ThisAppCustomIconsSource.pinboardAlt4,
    // ThisAppCustomIconsSource.pinboardAlt5,
    // ThisAppCustomIconsSource.pinboardAlt6,
    // ThisAppCustomIconsSource.pinboardAlt7,
    // ThisAppCustomIconsSource.pinboardAlt8,
    // ThisAppCustomIconsSource.pinboardAlt9,
    // ThisAppCustomIconsSource.pinboardAlt10,
    // ThisAppCustomIconsSource.pinboardSlash,
    // ThisAppCustomIconsSource.pinboardSlash2,
    // ThisAppCustomIconsSource.pinboardSlash3,
    // ThisAppCustomIconsSource.pinboardSlash4,
    // ThisAppCustomIconsSource.pinboardSlash5,
    // ThisAppCustomIconsSource.pinSlash,
    // ThisAppCustomIconsSource.pinSlash2,
    // ThisAppCustomIconsSource.pinSlash3,
    // ThisAppCustomIconsSource.pinSlash4,
    // ThisAppCustomIconsSource.pinSlash5,
    // ThisAppCustomIconsSource.plane,
    ThisAppCustomIconsSource.play,
    ThisAppCustomIconsSource.playAlt,
    ThisAppCustomIconsSource.plus,
    ThisAppCustomIconsSource.plusAlt,
    ThisAppCustomIconsSource.plusSmall,
    // ThisAppCustomIconsSource.power,
    ThisAppCustomIconsSource.printAlt,
    ThisAppCustomIconsSource.project,
    ThisAppCustomIconsSource.pulse,
    // ThisAppCustomIconsSource.radio,
    // ThisAppCustomIconsSource.radioAlt,
    // ThisAppCustomIconsSource.radioAlt2,
    // ThisAppCustomIconsSource.radioAlt3,
    // ThisAppCustomIconsSource.radioAlt4,
    // ThisAppCustomIconsSource.radioAlt5,
    // ThisAppCustomIconsSource.radioAlt6,
    // ThisAppCustomIconsSource.radioAlt7,
    // ThisAppCustomIconsSource.radioAlt8,
    // ThisAppCustomIconsSource.radioAlt9,
    // ThisAppCustomIconsSource.radioAlt10,
    // ThisAppCustomIconsSource.radioSlash,
    // ThisAppCustomIconsSource.radioSlash2,
    // ThisAppCustomIconsSource.radioSlash3,
    // ThisAppCustomIconsSource.radioSlash4,
    // ThisAppCustomIconsSource.radioSlash5,
    ThisAppCustomIconsSource.radioTower,
    ThisAppCustomIconsSource.rainbow,
    // ThisAppCustomIconsSource.rainbowAlt,
    // ThisAppCustomIconsSource.rainbowAlt2,
    // ThisAppCustomIconsSource.rainbowAlt3,
    // ThisAppCustomIconsSource.rainbowAlt4,
    // ThisAppCustomIconsSource.rainbowAlt5,
    // ThisAppCustomIconsSource.rainbowAlt6,
    // ThisAppCustomIconsSource.rainbowAlt7,
    // ThisAppCustomIconsSource.rainbowAlt8,
    // ThisAppCustomIconsSource.rainbowAlt9,
    // ThisAppCustomIconsSource.rainbowAlt10,
    // ThisAppCustomIconsSource.rainbowSlash,
    // ThisAppCustomIconsSource.rainbowSlash2,
    // ThisAppCustomIconsSource.rainbowSlash3,
    // ThisAppCustomIconsSource.rainbowSlash4,
    ThisAppCustomIconsSource.rainbowSlash5,
    ThisAppCustomIconsSource.reddit,
    ThisAppCustomIconsSource.repo,
    ThisAppCustomIconsSource.repoClone,
    ThisAppCustomIconsSource.repoForcePush,
    ThisAppCustomIconsSource.repoForked,
    ThisAppCustomIconsSource.repoPull,
    ThisAppCustomIconsSource.repoPush,
    ThisAppCustomIconsSource.repoTemplate,
    ThisAppCustomIconsSource.repoTemplatePrivate,
    ThisAppCustomIconsSource.reply,
    ThisAppCustomIconsSource.replyAlt,
    ThisAppCustomIconsSource.requestChanges,
    ThisAppCustomIconsSource.retina,
    ThisAppCustomIconsSource.retinaAlt,
    ThisAppCustomIconsSource.retinaAlt2,
    ThisAppCustomIconsSource.retinaAlt3,
    ThisAppCustomIconsSource.retinaAlt4,
    ThisAppCustomIconsSource.retinaAlt5,
    ThisAppCustomIconsSource.retinaAlt6,
    ThisAppCustomIconsSource.retinaAlt7,
    ThisAppCustomIconsSource.retinaAlt8,
    ThisAppCustomIconsSource.retinaAlt9,
    ThisAppCustomIconsSource.retinaAlt10,
    ThisAppCustomIconsSource.retinaSlash,
    ThisAppCustomIconsSource.retinaSlash2,
    ThisAppCustomIconsSource.retinaSlash3,
    ThisAppCustomIconsSource.retinaSlash4,
    ThisAppCustomIconsSource.retinaSlash5,
    ThisAppCustomIconsSource.retweet,
    ThisAppCustomIconsSource.rightBold,
    ThisAppCustomIconsSource.rightFat,
    ThisAppCustomIconsSource.rightOpen,
    ThisAppCustomIconsSource.right,
    ThisAppCustomIconsSource.rocket,
    ThisAppCustomIconsSource.rss,
    ThisAppCustomIconsSource.ruler,
    ThisAppCustomIconsSource.ruby,
    ThisAppCustomIconsSource.saved,
    ThisAppCustomIconsSource.scale,
    ThisAppCustomIconsSource.scaleAlt,
    ThisAppCustomIconsSource.scaleAlt2,
    ThisAppCustomIconsSource.scaleAlt3,
    ThisAppCustomIconsSource.scaleAlt4,
    ThisAppCustomIconsSource.scaleAlt5,
    ThisAppCustomIconsSource.scaleAlt6,
    ThisAppCustomIconsSource.scaleAlt7,
    // ThisAppCustomIconsSource.scaleAlt8,
    // ThisAppCustomIconsSource.scaleAlt9,
    ThisAppCustomIconsSource.scaleAlt10,
    ThisAppCustomIconsSource.scaleSlash,
    ThisAppCustomIconsSource.scaleSlash2,
    ThisAppCustomIconsSource.scaleSlash3,
    ThisAppCustomIconsSource.scaleSlash4,
    ThisAppCustomIconsSource.scaleSlash5,
    ThisAppCustomIconsSource.search,
    ThisAppCustomIconsSource.searchAlt,
    ThisAppCustomIconsSource.server,
    ThisAppCustomIconsSource.settings,
    ThisAppCustomIconsSource.shield,
    ThisAppCustomIconsSource.shieldCheck,
    ThisAppCustomIconsSource.shieldLock,
    ThisAppCustomIconsSource.shieldX,
    ThisAppCustomIconsSource.shuffle,
    ThisAppCustomIconsSource.signIn,
    ThisAppCustomIconsSource.signOut,
    ThisAppCustomIconsSource.skip,
    ThisAppCustomIconsSource.smiley,
    ThisAppCustomIconsSource.spin3,
    ThisAppCustomIconsSource.spin4,
    ThisAppCustomIconsSource.spin5,
    ThisAppCustomIconsSource.spin6,
    ThisAppCustomIconsSource.spinner1,
    ThisAppCustomIconsSource.spinnerAlt,
    ThisAppCustomIconsSource.square,
    ThisAppCustomIconsSource.star,
    ThisAppCustomIconsSource.starAlt,
    ThisAppCustomIconsSource.starEmpty,
    ThisAppCustomIconsSource.stop,
    ThisAppCustomIconsSource.stopAlt,
    ThisAppCustomIconsSource.stopwatch,
    ThisAppCustomIconsSource.sync,
    ThisAppCustomIconsSource.tag,
    ThisAppCustomIconsSource.taskList,
    ThisAppCustomIconsSource.terminal,
    ThisAppCustomIconsSource.textSize,
    ThisAppCustomIconsSource.thumbsup,
    ThisAppCustomIconsSource.thumbsDown,
    ThisAppCustomIconsSource.thThumb,
    ThisAppCustomIconsSource.thThumbEmpty,
    ThisAppCustomIconsSource.thList,
    ThisAppCustomIconsSource.telescope,
    ThisAppCustomIconsSource.toEnd,
    ThisAppCustomIconsSource.tools,
    ThisAppCustomIconsSource.toStart,
    ThisAppCustomIconsSource.trash,
    ThisAppCustomIconsSource.trashcan,
    ThisAppCustomIconsSource.trophy,
    ThisAppCustomIconsSource.triangleDown,
    ThisAppCustomIconsSource.triangleLeft,
    ThisAppCustomIconsSource.triangleRight,
    ThisAppCustomIconsSource.triangleUp,
    ThisAppCustomIconsSource.twitter,
    ThisAppCustomIconsSource.twitterCircled,
    ThisAppCustomIconsSource.unfold,
    ThisAppCustomIconsSource.unMute,
    ThisAppCustomIconsSource.unverified,
    ThisAppCustomIconsSource.unsaved,
    ThisAppCustomIconsSource.upBold,
    ThisAppCustomIconsSource.upFat,
    ThisAppCustomIconsSource.upOpen,
    ThisAppCustomIconsSource.up,
    ThisAppCustomIconsSource.user,
    ThisAppCustomIconsSource.users,
    ThisAppCustomIconsSource.verified,
    ThisAppCustomIconsSource.vector,
    ThisAppCustomIconsSource.vectorPencil,
    ThisAppCustomIconsSource.versions,
    ThisAppCustomIconsSource.workflow,
    ThisAppCustomIconsSource.workflowAll,
    ThisAppCustomIconsSource.x,
    ThisAppCustomIconsSource.zoomIn,
    ThisAppCustomIconsSource.zoomOut,
    ThisAppCustomIconsSource.zap,

//
  ];
//
  List<IconData> get myCustomIconsList => _myCustomIconList;
}
