import 'package:flutter/material.dart';

import 'custom_icons_src.dart';

class ThisAppCustomIcons {
  static const List<IconData> _myCustomIconList = [
    ThisAppIcons.alert,
    ThisAppIcons.anchor,
    ThisAppIcons.archive,
    ThisAppIcons.arrowBoth,
    ThisAppIcons.arrowDown,
    ThisAppIcons.arrowLeft,
    ThisAppIcons.arrowRight,
    ThisAppIcons.arrowSmallDown,
    ThisAppIcons.arrowSmallLeft,
    ThisAppIcons.arrowSmallRight,
    ThisAppIcons.arrowSmallUp,
    ThisAppIcons.arrowUp,
    ThisAppIcons.at,
    ThisAppIcons.attach,
    ThisAppIcons.attention,
    ThisAppIcons.attentionAlt,
    ThisAppIcons.beaker,
    ThisAppIcons.bell,
    ThisAppIcons.bellAlt,
    ThisAppIcons.book,
    ThisAppIcons.bookmark,
    ThisAppIcons.briefcase,
    ThisAppIcons.browser,
    ThisAppIcons.bug,
    ThisAppIcons.cancel,
    ThisAppIcons.cancelCircled,
    ThisAppIcons.calendar,
    ThisAppIcons.calendarAlt,
    ThisAppIcons.camera,
    ThisAppIcons.chartBar,
    ThisAppIcons.check,
    ThisAppIcons.checklist,
    ThisAppIcons.chevronDown,
    ThisAppIcons.chevronLeft,
    ThisAppIcons.chevronRight,
    ThisAppIcons.chevronUp,
    ThisAppIcons.chrome,
    ThisAppIcons.circleSlash,
    ThisAppIcons.clippy,
    ThisAppIcons.clock,
    ThisAppIcons.clockAlt,
    ThisAppIcons.cloud,
    ThisAppIcons.cloudDownload,
    ThisAppIcons.cloudUpload,
    ThisAppIcons.cog,
    ThisAppIcons.colorAdjust,
    ThisAppIcons.comment,
    ThisAppIcons.commentAlt,
    ThisAppIcons.commentDiscussion,
    ThisAppIcons.connectedObject,
    // ThisAppIcons.console,
    ThisAppIcons.coverFlow,
    ThisAppIcons.coverFlowEmpty,
    ThisAppIcons.creditCard,
    ThisAppIcons.crown,
    ThisAppIcons.crownMinus,
    ThisAppIcons.crownPlus,
    // ThisAppIcons.css,
    ThisAppIcons.dashboard,
    ThisAppIcons.dataScience,
    ThisAppIcons.dataScienceInv,
    ThisAppIcons.database,
    ThisAppIcons.dependent,
    ThisAppIcons.desktopDownload,
    ThisAppIcons.deviceCamera,
    ThisAppIcons.deviceCameraVideo,
    ThisAppIcons.deviceDesktop,
    ThisAppIcons.deviceMobile,
    ThisAppIcons.diff,
    ThisAppIcons.diffAdded,
    ThisAppIcons.diffIgnored,
    ThisAppIcons.diffModified,
    ThisAppIcons.diffRemoved,
    ThisAppIcons.diffRenamed,
    ThisAppIcons.doc,
    ThisAppIcons.download,
    ThisAppIcons.downloadCloud,
    ThisAppIcons.downBold,
    ThisAppIcons.downFat,
    ThisAppIcons.downOpen,
    ThisAppIcons.down,
    ThisAppIcons.ellipsis,
    ThisAppIcons.emoAngry,
    ThisAppIcons.emoBeer,
    ThisAppIcons.emoCoffee,
    ThisAppIcons.emoCry,
    ThisAppIcons.emoDevil,
    ThisAppIcons.emoDispleased,
    ThisAppIcons.emoGrin,
    ThisAppIcons.emoHappy,
    ThisAppIcons.emoLaugh,
    ThisAppIcons.emoSaint,
    ThisAppIcons.emoShoot,
    ThisAppIcons.emoSleep,
    ThisAppIcons.emoSquint,
    ThisAppIcons.emoSunglasses,
    ThisAppIcons.emoSurprised,
    ThisAppIcons.emoThumbsup,
    ThisAppIcons.emoTongue,
    ThisAppIcons.emoUnhappy,
    ThisAppIcons.emoWink,
    ThisAppIcons.emoWinkAlt,
    ThisAppIcons.export,
    ThisAppIcons.eye,
    ThisAppIcons.eyeAlt,
    ThisAppIcons.eyeClosed,
    ThisAppIcons.fileBinary,
    ThisAppIcons.fileCode,
    ThisAppIcons.fileDirectory,
    ThisAppIcons.fileMedia,
    ThisAppIcons.filePdf,
    ThisAppIcons.fileSubmodule,
    ThisAppIcons.fileSymlinkDirectory,
    ThisAppIcons.fileSymlinkFile,
    ThisAppIcons.fileZip,
    ThisAppIcons.fire,
    ThisAppIcons.flash,
    ThisAppIcons.fold,
    ThisAppIcons.foldDown,
    ThisAppIcons.folder,
    ThisAppIcons.folderEmpty,
    ThisAppIcons.folderOpen,
    ThisAppIcons.folderOpenEmpty,
    ThisAppIcons.foldUp,
    ThisAppIcons.fontSize,
    // ThisAppIcons.fuel,
    ThisAppIcons.gift,
    ThisAppIcons.github,
    ThisAppIcons.githubAction,
    ThisAppIcons.githubCircled,
    ThisAppIcons.githubCircledAlt,
    ThisAppIcons.githubCircledAlt2,
    ThisAppIcons.gist,
    ThisAppIcons.gistSecret,
    ThisAppIcons.gitBranch,
    ThisAppIcons.gitCommit,
    ThisAppIcons.gitCompare,
    ThisAppIcons.gitMerge,
    ThisAppIcons.gitPullRequest,
    ThisAppIcons.globe,
    ThisAppIcons.globeAlt,
    ThisAppIcons.globeInv,
    ThisAppIcons.graph,
    ThisAppIcons.hash,
    ThisAppIcons.heart,
    ThisAppIcons.heartAlt,
    ThisAppIcons.heartBroken,
    ThisAppIcons.heartOutline,
    ThisAppIcons.helpCircled,
    ThisAppIcons.helpCircledAlt,
    ThisAppIcons.history,
    ThisAppIcons.home,
    ThisAppIcons.homeAlt,
    ThisAppIcons.hourglass,
    ThisAppIcons.hubot,
    ThisAppIcons.inbox,
    ThisAppIcons.inboxAlt,
    ThisAppIcons.infinity,
    ThisAppIcons.info,
    ThisAppIcons.infoCircled,
    ThisAppIcons.infoCircledAlt,
    ThisAppIcons.internalRepo,
    ThisAppIcons.isSight,
    ThisAppIcons.issueClosed,
    ThisAppIcons.issueOpened,
    ThisAppIcons.issueReOpened,
    // ThisAppIcons.it,
    // ThisAppIcons.itAlt,
    ThisAppIcons.jersey,
    ThisAppIcons.joystick,
    // ThisAppIcons.js,
    // ThisAppIcons.jsAlt,
    ThisAppIcons.key,
    ThisAppIcons.keyboard,
    ThisAppIcons.king,
    // ThisAppIcons.laptop,
    ThisAppIcons.leftBold,
    ThisAppIcons.leftFat,
    ThisAppIcons.leftOpen,
    ThisAppIcons.left,
    ThisAppIcons.lineArrowDown,
    ThisAppIcons.lineArrowLeft,
    ThisAppIcons.lineArrowRight,
    ThisAppIcons.lineArrowUp,
    ThisAppIcons.link,
    ThisAppIcons.linkAlt,
    ThisAppIcons.linkAlt,
    ThisAppIcons.linkExternal,
    ThisAppIcons.listOrdered,
    ThisAppIcons.listUnordered,
    ThisAppIcons.location,
    ThisAppIcons.locationAlt,
    ThisAppIcons.lock,
    ThisAppIcons.lockAlt,
    ThisAppIcons.lockAlt2,
    ThisAppIcons.lockOpen,
    ThisAppIcons.lockOpenAlt,
    ThisAppIcons.logIn,
    ThisAppIcons.logOut,
    ThisAppIcons.mail,
    ThisAppIcons.mailAlt,
    ThisAppIcons.mailRead,
    ThisAppIcons.male,
    ThisAppIcons.map,
    ThisAppIcons.markdown,
    ThisAppIcons.markGithub,
    ThisAppIcons.marquee,
    ThisAppIcons.math,
    ThisAppIcons.mathCircled,
    ThisAppIcons.mathCircledEmpty,
    ThisAppIcons.megaphone,
    ThisAppIcons.menu,
    ThisAppIcons.mfgLogo,
    ThisAppIcons.mfgLogoCircled,
    ThisAppIcons.microchip,
    ThisAppIcons.microphone,
    // ThisAppIcons.microphoneAlt,
    // ThisAppIcons.microphoneAlt2,
    ThisAppIcons.microphoneAlt3,
    ThisAppIcons.microphoneAlt4,
    // ThisAppIcons.microphoneAlt5,
    ThisAppIcons.microphoneAlt7,
    ThisAppIcons.microphoneAlt8,
    // ThisAppIcons.microphoneAlt9,
    ThisAppIcons.microphoneOff,
    ThisAppIcons.microphoneSlash,
    ThisAppIcons.microphoneSlash2,
    ThisAppIcons.microphoneSlash3,
    ThisAppIcons.microphoneSlash4,
    // ThisAppIcons.microphoneSlash5,
    ThisAppIcons.mirror,
    ThisAppIcons.minus,
    ThisAppIcons.minusAlt,
    ThisAppIcons.minusAlt2,
    ThisAppIcons.minusAlt3,
    ThisAppIcons.minusAlt4,
    ThisAppIcons.minusCircled,
    ThisAppIcons.minusCircledAlt,
    ThisAppIcons.minusCircledAlt2,
    ThisAppIcons.minusCircledAlt3,
    ThisAppIcons.minusCircledAlt4,
    ThisAppIcons.minusSmall,
    ThisAppIcons.minusSmallAlt,
    ThisAppIcons.minusSmallAlt2,
    ThisAppIcons.minusSmallAlt3,
    ThisAppIcons.minusSmallAlt,
    ThisAppIcons.monitor,
    ThisAppIcons.mortarBoard,
    // ThisAppIcons.mousePointer,
    ThisAppIcons.movie,
    // ThisAppIcons.musicNote,
    // ThisAppIcons.musicNoteAlt,
    // ThisAppIcons.musicNoteAlt2,
    // ThisAppIcons.musicNoteAlt3,
    // ThisAppIcons.musicNoteAlt4,
    // ThisAppIcons.musicNoteAlt5,
    // ThisAppIcons.musicNoteAlt6,
    // ThisAppIcons.musicNoteAlt7,
    // ThisAppIcons.musicNoteAlt8,
    // ThisAppIcons.musicNoteAlt9,
    // ThisAppIcons.musicNoteAltSlash,
    // ThisAppIcons.musicNoteAltSlash2,
    // ThisAppIcons.musicNoteAltSlash3,
    // ThisAppIcons.musicNoteAltSlash4,
    // ThisAppIcons.musicNoteAltSlash5,
    // ThisAppIcons.musicNoteSlash,
    // ThisAppIcons.musicNoteSlash2,
    // ThisAppIcons.musicNoteSlash3,
    // ThisAppIcons.musicNoteSlash4,
    // ThisAppIcons.musicNoteSlash5,
    // ThisAppIcons.myCustomIconList,
    // ThisAppIcons.navbar,
    // ThisAppIcons.navbarAlt,
    // ThisAppIcons.navbarAlt2,
    // ThisAppIcons.navbarAlt3,
    // ThisAppIcons.navbarAlt4,
    // ThisAppIcons.navbarAlt5,
    // ThisAppIcons.navbarAlt6,
    // ThisAppIcons.navbarAlt7,
    // ThisAppIcons.navbarAlt8,
    // ThisAppIcons.navbarAlt9,
    ThisAppIcons.note,
    // ThisAppIcons.notebook,
    // ThisAppIcons.notebookAlt,
    // ThisAppIcons.notebookAlt2,
    // ThisAppIcons.notebookAlt3,
    // ThisAppIcons.notebookAlt4,
    // ThisAppIcons.notebookAlt5,
    // ThisAppIcons.notebookSlash,
    // ThisAppIcons.notebookSlash2,
    // ThisAppIcons.notebookSlash3,
    // ThisAppIcons.notebookSlash4,
    // ThisAppIcons.notebookSlash5,
    // ThisAppIcons.notebookAlt6,
    // ThisAppIcons.notebookAlt7,
    // ThisAppIcons.notebookAlt8,
    // ThisAppIcons.notebookAlt9,
    // ThisAppIcons.notebookAlt10,
    // ThisAppIcons.noteSlash,
    // ThisAppIcons.noteSlash2,
    // ThisAppIcons.noteSlash3,
    // ThisAppIcons.noteSlash4,
    // ThisAppIcons.noteSlash5,
    ThisAppIcons.paintCan,
    // ThisAppIcons.paperClip,
    // ThisAppIcons.paperClipAlt,
    // ThisAppIcons.paperClipAlt2,
    // ThisAppIcons.paperClipAlt3,
    // ThisAppIcons.paperClipAlt4,
    // ThisAppIcons.paperClipAlt5,
    // ThisAppIcons.paperClipAlt6,
    // ThisAppIcons.paperClipAlt7,
    // ThisAppIcons.paperClipAlt8,
    // ThisAppIcons.paperClipAlt9,
    // ThisAppIcons.paperClipAlt10,
    // ThisAppIcons.paperClipSlash,
    // ThisAppIcons.paperClipSlash2,
    // ThisAppIcons.paperClipSlash3,
    // ThisAppIcons.paperClipSlash4,
    // ThisAppIcons.paperClipSlash5,
    ThisAppIcons.paperPlane,
    ThisAppIcons.paperPlaneAlt,
    ThisAppIcons.paperPlaneAlt2,
    ThisAppIcons.pause,
    ThisAppIcons.pencil,
    ThisAppIcons.pencilAlt,
    ThisAppIcons.person,
    ThisAppIcons.pin,
    // ThisAppIcons.pinboard,
    // ThisAppIcons.pinboardAlt1,
    // ThisAppIcons.pinboardAlt2,
    // ThisAppIcons.pinboardAlt3,
    // ThisAppIcons.pinboardAlt4,
    // ThisAppIcons.pinboardAlt5,
    // ThisAppIcons.pinboardAlt6,
    // ThisAppIcons.pinboardAlt7,
    // ThisAppIcons.pinboardAlt8,
    // ThisAppIcons.pinboardAlt9,
    // ThisAppIcons.pinboardAlt10,
    // ThisAppIcons.pinboardSlash,
    // ThisAppIcons.pinboardSlash2,
    // ThisAppIcons.pinboardSlash3,
    // ThisAppIcons.pinboardSlash4,
    // ThisAppIcons.pinboardSlash5,
    // ThisAppIcons.pinSlash,
    // ThisAppIcons.pinSlash2,
    // ThisAppIcons.pinSlash3,
    // ThisAppIcons.pinSlash4,
    // ThisAppIcons.pinSlash5,
    // ThisAppIcons.plane,
    ThisAppIcons.play,
    ThisAppIcons.playAlt,
    ThisAppIcons.plus,
    ThisAppIcons.plusAlt,
    ThisAppIcons.plusSmall,
    // ThisAppIcons.power,
    ThisAppIcons.printAlt,
    ThisAppIcons.project,
    ThisAppIcons.pulse,
    // ThisAppIcons.radio,
    // ThisAppIcons.radioAlt,
    // ThisAppIcons.radioAlt2,
    // ThisAppIcons.radioAlt3,
    // ThisAppIcons.radioAlt4,
    // ThisAppIcons.radioAlt5,
    // ThisAppIcons.radioAlt6,
    // ThisAppIcons.radioAlt7,
    // ThisAppIcons.radioAlt8,
    // ThisAppIcons.radioAlt9,
    // ThisAppIcons.radioAlt10,
    // ThisAppIcons.radioSlash,
    // ThisAppIcons.radioSlash2,
    // ThisAppIcons.radioSlash3,
    // ThisAppIcons.radioSlash4,
    // ThisAppIcons.radioSlash5,
    ThisAppIcons.radioTower,
    // ThisAppIcons.rainbow,
    // ThisAppIcons.rainbowAlt,
    // ThisAppIcons.rainbowAlt2,
    // ThisAppIcons.rainbowAlt3,
    // ThisAppIcons.rainbowAlt4,
    // ThisAppIcons.rainbowAlt5,
    // ThisAppIcons.rainbowAlt6,
    // ThisAppIcons.rainbowAlt7,
    // ThisAppIcons.rainbowAlt8,
    // ThisAppIcons.rainbowAlt9,
    // ThisAppIcons.rainbowAlt10,
    // ThisAppIcons.rainbowSlash,
    // ThisAppIcons.rainbowSlash2,
    // ThisAppIcons.rainbowSlash3,
    // ThisAppIcons.rainbowSlash4,
    ThisAppIcons.rainbowSlash5,
    ThisAppIcons.reddit,
    ThisAppIcons.repo,
    ThisAppIcons.repoClone,
    ThisAppIcons.repoForcePush,
    ThisAppIcons.repoForked,
    ThisAppIcons.repoPull,
    ThisAppIcons.repoPush,
    ThisAppIcons.repoTemplate,
    ThisAppIcons.repoTemplatePrivate,
    ThisAppIcons.reply,
    ThisAppIcons.replyAlt,
    ThisAppIcons.requestChanges,
    ThisAppIcons.retina,
    ThisAppIcons.retinaAlt,
    ThisAppIcons.retinaAlt2,
    ThisAppIcons.retinaAlt3,
    ThisAppIcons.retinaAlt4,
    ThisAppIcons.retinaAlt5,
    ThisAppIcons.retinaAlt6,
    ThisAppIcons.retinaAlt7,
    ThisAppIcons.retinaAlt8,
    ThisAppIcons.retinaAlt9,
    ThisAppIcons.retinaAlt10,
    ThisAppIcons.retinaSlash,
    ThisAppIcons.retinaSlash2,
    ThisAppIcons.retinaSlash3,
    ThisAppIcons.retinaSlash4,
    // ThisAppIcons.retinaSlash5,
    ThisAppIcons.retweet,
    ThisAppIcons.rightBold,
    ThisAppIcons.rightFat,
    ThisAppIcons.rightOpen,
    ThisAppIcons.right,
    ThisAppIcons.rocket,
    ThisAppIcons.rss,
    ThisAppIcons.ruler,
    ThisAppIcons.ruby,
    ThisAppIcons.saved,
    // ThisAppIcons.scale,
    ThisAppIcons.scaleAlt,
    ThisAppIcons.scaleAlt2,
    ThisAppIcons.scaleAlt3,
    ThisAppIcons.scaleAlt4,
    ThisAppIcons.scaleAlt5,
    ThisAppIcons.scaleAlt6,
    ThisAppIcons.scaleAlt7,
    // ThisAppIcons.scaleAlt8,
    // ThisAppIcons.scaleAlt9,
    ThisAppIcons.scaleAlt10,
    ThisAppIcons.scaleSlash,
    ThisAppIcons.scaleSlash2,
    ThisAppIcons.scaleSlash3,
    ThisAppIcons.scaleSlash4,
    ThisAppIcons.scaleSlash5,
    ThisAppIcons.search,
    ThisAppIcons.searchAlt,
    ThisAppIcons.server,
    ThisAppIcons.settings,
    ThisAppIcons.shield,
    ThisAppIcons.shieldCheck,
    ThisAppIcons.shieldLock,
    ThisAppIcons.shieldX,
    ThisAppIcons.shuffle,
    ThisAppIcons.signIn,
    ThisAppIcons.signOut,
    ThisAppIcons.skip,
    ThisAppIcons.smiley,
    ThisAppIcons.spin3,
    ThisAppIcons.spin4,
    ThisAppIcons.spin5,
    ThisAppIcons.spin6,
    ThisAppIcons.spinner1,
    ThisAppIcons.spinnerAlt,
    // ThisAppIcons.square,
    ThisAppIcons.star,
    ThisAppIcons.starAlt,
    ThisAppIcons.starEmpty,
    ThisAppIcons.stop,
    ThisAppIcons.stopAlt,
    ThisAppIcons.stopwatch,
    ThisAppIcons.sync,
    ThisAppIcons.tag,
    ThisAppIcons.taskList,
    ThisAppIcons.terminal,
    ThisAppIcons.textSize,
    ThisAppIcons.thumbsup,
    ThisAppIcons.thumbsDown,
    ThisAppIcons.thThumb,
    ThisAppIcons.thThumbEmpty,
    ThisAppIcons.thList,
    ThisAppIcons.telescope,
    ThisAppIcons.toEnd,
    ThisAppIcons.tools,
    ThisAppIcons.toStart,
    ThisAppIcons.trash,
    ThisAppIcons.trashcan,
    ThisAppIcons.trophy,
    ThisAppIcons.triangleDown,
    ThisAppIcons.triangleLeft,
    ThisAppIcons.triangleRight,
    ThisAppIcons.triangleUp,
    ThisAppIcons.twitter,
    ThisAppIcons.twitterCircled,
    ThisAppIcons.unfold,
    ThisAppIcons.unMute,
    ThisAppIcons.unverified,
    ThisAppIcons.unsaved,
    ThisAppIcons.upBold,
    ThisAppIcons.upFat,
    ThisAppIcons.upOpen,
    ThisAppIcons.up,
    ThisAppIcons.user,
    ThisAppIcons.users,
    ThisAppIcons.verified,
    ThisAppIcons.vector,
    ThisAppIcons.vectorPencil,
    ThisAppIcons.versions,
    ThisAppIcons.workflow,
    ThisAppIcons.workflowAll,
    ThisAppIcons.x,
    ThisAppIcons.zoomIn,
    ThisAppIcons.zoomOut,
    ThisAppIcons.zap,

//
  ];
//
  List<IconData> get myCustomIconsList => _myCustomIconList;
}
