// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7tsPED3n5T8lCxo7JsDCSPI21RifZICg',
    appId: '1:526635916196:web:591560131b85f4fb6aff31',
    messagingSenderId: '526635916196',
    projectId: 'my-blueprint-for-apps',
    authDomain: 'my-blueprint-for-apps.firebaseapp.com',
    storageBucket: 'my-blueprint-for-apps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQrjBILfcPgPr_ZfXH62pqWrS92f5Et-Q',
    appId: '1:526635916196:android:4395f73df8ff4f5e6aff31',
    messagingSenderId: '526635916196',
    projectId: 'my-blueprint-for-apps',
    storageBucket: 'my-blueprint-for-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhdER8J2snLcqJY8hwre3l2eR_qxLRCvI',
    appId: '1:526635916196:ios:216f3d715458d2bf6aff31',
    messagingSenderId: '526635916196',
    projectId: 'my-blueprint-for-apps',
    storageBucket: 'my-blueprint-for-apps.appspot.com',
    iosBundleId: 'com.example.blueprintApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhdER8J2snLcqJY8hwre3l2eR_qxLRCvI',
    appId: '1:526635916196:ios:548166a5c2da1c1e6aff31',
    messagingSenderId: '526635916196',
    projectId: 'my-blueprint-for-apps',
    storageBucket: 'my-blueprint-for-apps.appspot.com',
    iosBundleId: 'com.example.blueprintApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7tsPED3n5T8lCxo7JsDCSPI21RifZICg',
    appId: '1:526635916196:web:4d32d36d032a4ace6aff31',
    messagingSenderId: '526635916196',
    projectId: 'my-blueprint-for-apps',
    authDomain: 'my-blueprint-for-apps.firebaseapp.com',
    storageBucket: 'my-blueprint-for-apps.appspot.com',
  );
}


/*
Platform  Firebase App Id
web       1:526635916196:web:591560131b85f4fb6aff31
android   1:526635916196:android:4395f73df8ff4f5e6aff31
ios       1:526635916196:ios:216f3d715458d2bf6aff31
macos     1:526635916196:ios:548166a5c2da1c1e6aff31
windows   1:526635916196:web:4d32d36d032a4ace6aff31

Certificate fingerprints:
         SHA1: B4:B8:74:26:A4:86:04:3A:74:B6:30:22:B8:83:A2:95:8F:2E:40:89
         SHA256: 31:75:61:7C:77:FA:74:94:E3:9A:B2:47:6A:4C:DF:50:48:0A:07:83:E9:D3:42:C9:EF:F6:51:18:FC:A9:FE:BA

 */