// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Eq8Wa590zf-UzGaqG7iDOQ36o3XlSxQ',
    appId: '1:120549187583:web:e7834fb833f547cf8591ca',
    messagingSenderId: '120549187583',
    projectId: 'blueprint-app-6b9aa',
    authDomain: 'blueprint-app-6b9aa.firebaseapp.com',
    storageBucket: 'blueprint-app-6b9aa.appspot.com',
    measurementId: 'G-CB17BNDBJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0rgdgiwcAa2GxDcukfaT-WlaM8d-wJI',
    appId: '1:120549187583:android:3ac2d7a1758ad0ba8591ca',
    messagingSenderId: '120549187583',
    projectId: 'blueprint-app-6b9aa',
    storageBucket: 'blueprint-app-6b9aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdJcNq-t89-1d-ooL13Hxq6BfeLRzr2EY',
    appId: '1:120549187583:ios:b0f35ed7a2f8cc8a8591ca',
    messagingSenderId: '120549187583',
    projectId: 'blueprint-app-6b9aa',
    storageBucket: 'blueprint-app-6b9aa.appspot.com',
    iosBundleId: 'com.example.blueprintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdJcNq-t89-1d-ooL13Hxq6BfeLRzr2EY',
    appId: '1:120549187583:ios:b9b99ff954a431f98591ca',
    messagingSenderId: '120549187583',
    projectId: 'blueprint-app-6b9aa',
    storageBucket: 'blueprint-app-6b9aa.appspot.com',
    iosBundleId: 'com.example.blueprintApp.RunnerTests',
  );
}

//
class FireBaseConst {
  static const String oAuthClientIDdForAndroid =
      "120549187583-dvrfmp1m3aqo5mor8joojh6vs434isnb.apps.googleusercontent.com";
  static const String oAuthClientIDdForIOS =
      "120549187583-o997pto2a1aogvn5t9t467hgchgs8dak.apps.googleusercontent.com";
  static const String oAuthClientIDdForIOSForRunnerTests =
      "120549187583-vlei4beiob6kf5othgodlqhadiqp0mej.apps.googleusercontent.com";
  static const String oAuthClientIDdForWeb =
      "120549187583-32d3pnvlakm36ol163f2fus09kh1nbkp.apps.googleusercontent.com";
/*
SHA1: B4:B8:74:26:A4:86:04:3A:74:B6:30:22:B8:83:A2:95:8F:2E:40:89
SHA256: 31:75:61:7C:77:FA:74:94:E3:9A:B2:47:6A:4C:DF:50:48:0A:07:83:E9:D3:42:C9:EF:F6:51:18:FC:A9:FE:BA

Platform  Firebase App Id
web       1:120549187583:web:e7834fb833f547cf8591ca
android   1:120549187583:android:3ac2d7a1758ad0ba8591ca
ios       1:120549187583:ios:b0f35ed7a2f8cc8a8591ca
macos     1:120549187583:ios:b9b99ff954a431f98591ca
 */
}
