// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Eq8Wa590zf-UzGaqG7iDOQ36o3XlSxQ',
    appId: '1:120549187583:web:e7834fb833f547cf8591ca',
    messagingSenderId: '120549187583',
    projectId: 'blueprint-app-6b9aa',
    authDomain: 'blueprint-app-6b9aa.firebaseapp.com',
    storageBucket: 'blueprint-app-6b9aa.appspot.com',
    measurementId: 'G-CB17BNDBJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0rgdgiwcAa2GxDcukfaT-WlaM8d-wJI',
    appId: '1:120549187583:android:3ac2d7a1758ad0ba8591ca',
    messagingSenderId: '120549187583',
    projectId: 'blueprint-app-6b9aa',
    storageBucket: 'blueprint-app-6b9aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdJcNq-t89-1d-ooL13Hxq6BfeLRzr2EY',
    appId: '1:120549187583:ios:b0f35ed7a2f8cc8a8591ca',
    messagingSenderId: '120549187583',
    projectId: 'blueprint-app-6b9aa',
    storageBucket: 'blueprint-app-6b9aa.appspot.com',
    iosBundleId: 'com.example.blueprintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdJcNq-t89-1d-ooL13Hxq6BfeLRzr2EY',
    appId: '1:120549187583:ios:b9b99ff954a431f98591ca',
    messagingSenderId: '120549187583',
    projectId: 'blueprint-app-6b9aa',
    storageBucket: 'blueprint-app-6b9aa.appspot.com',
    iosBundleId: 'com.example.blueprintApp.RunnerTests',
  );
}
